### ISSUE TITLE
Update Github action for AWS creds

### ISSUE THREAD

**Issue by BlackText** [mihai-satmarean/sciitdevops#44]
Update Github action for AWS creds

**Comment by mihai-satmarean** [comment]
@BlackText Whom is to manage this issue?

**Comment by BlackText** [comment]
It's meant for me. WIP

**Comment by BlackText** [comment]
Updated [github-actions-demo.yml](https://github.com/mihai-satmarean/sciitdevops/blob/refs/heads/feature/44-github-secret/.github/workflows/github-actions-demo.yml). PR en route.
